### ISSUE TITLE
Is it ok if I add a gcsCommandQueue?

### ISSUE THREAD

**Issue by marton-demeter** [KittsSeniorDesign/DifferentialDrive#12]
This would store the packets created by Interpreter and would be consumed by the gcsCommBaseClass. If there's a queue/pipe already for that please let me know.

**Comment by marton-demeter** [comment]
And can I use gcsDataQueue for relaying position data to the UI and Pilot or does it have a different functionality. If i can't, is it ok if I create one for this purpose in util.py?

**Comment by RyanLoringCooper** [comment]
1. That code should be in a different repo, not the DifferentialDrive repo because it pertains to gcsDataQueue. Eventually all of the gcs stuff (data turbine, Matlab, ui, controller code, plus other) will get one repo, but for now they are spread out. I would like it if you made this repo. 
2. Yes please. That is what #4 is about.
